name: Build-develop

on:
  push:
    branches: 
      - develop
      
jobs:
  compile_css:
    runs-on: ubuntu-latest
    
    steps:
      - name: Node version
	run: node -v
        
      - name: ls -la 1
	run: ls -la 
        
      - name: Git clone my repo
	uses: actions/checkout@v1 
        
      - name: ls -la 2
	run: ls -la 
         
      - name: Install dependencies
        run: npm install
      
      - name: Execute building
        run: npm run prod
