name: Build-develop

on:
  push:
    branches: 
      - develop
  pull_request:
    branches: 
      - develop
    types: 
      - closed
      
jobs:
  compile_css:
    runs-on: ubuntu-latest
    
    steps:
      - name: Node version
        run: node -v
        
      - name: Git clone my repo
        uses: actions/checkout@v1 
        
#      - name: ls -la 2
#        run: ls -la 
         
      - name: Install dependencies
        run: npm install
      
      - name: Execute building
        run: npm run build
      
      - name: Push changes
      - uses: actions/checkout@v3
      - run: |
          git add ./public/
          git commit -m "generated"
          git push
