name: Build-develop

on:
  pull_request:
    branches: [develop]
    types: [closed]
      
jobs:
  compile_css1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Node version
        run: node -v
        
      - name: Git clone my repo
        uses: actions/checkout@v3 
        
      - name: ls -la 2
        run: ls -la 
         
      - name: Install dependencies
        run: npm install
      
      - name: Execute building
        run: npm run build
      
      - name: Push changes
        run: |
          git add ./public/
          git commit -m "generated1"
          git push
