name: Build-develop

on:
  pull_request:
    branches: [develop]
    types: [closed]
      
jobs:
  compile_public:
    runs-on: ubuntu-latest
    
    steps:
      - name: Node version
        run: node -v
        
      - name: Files in root direcory
        run: ls -la
        
      - name: Git clone my repo
        uses: actions/checkout@v3 
        
      - name: Files in public directory after PULL
        run: ls -la ./public
         
      - name: Install dependencies
        run: npm install
      
      - name: Execute building
        run: npm run build
      
      - name: Files in public directory after BUILD
        run: ls -la ./public
      
      - name: Push changes
        run: |
          git config --global user.name "Action"
          git config --global user.email "action@github.com"
          git add ./public
          git commit -m "Compiling public"
          git push
